### ISSUE TITLE
Rewrite specs to not stub database

### ISSUE THREAD

**Issue by mzikherman** [artsy/kaws#50]
Currently, the database and related methods are being stubbed. Since we're having an integration test anyway that runs a query against the schema (so not super unit-y), we should be able to assert database functionality is working. So actually save and retrieve objetcs, etc.

**Comment by mbilokonsky** [comment]
This spec finally adds an integration test that hits mongo directly. Moving forward we should probably do more of this! :)

https://github.com/artsy/kaws/pull/114

**Comment by mbilokonsky** [comment]
We now have this in place, even if we don't have all of the current tests running through it. Do we really want to rewrite all of our specs for this, @mzikherman, or for the purposes of this issue is it sufficient that we have the capacity to add new tests as Integration tests or unit tests? 

Me sense is that we shouldn't rewrite. Rewriting everything would be significant work, lead to a much longer test cycle length, and doesn't necessarily gain us anything - unit tests are still valuable, right? Rather, let's identify those areas that need e2e tests moving forward and make it a point to add them as they come up?
